version: '3'
services:
  
 gvm10:
    image: falkowich/gvm10:psql
      - 9391:9391
    restart: always
    volumes:
      - gvm:/usr/local/var/lib/gvm/
      - psql:/var/lib/postgresql/
volumes:
  gvm:
  psql: